### ISSUE TITLE
ENHANCEMENT: Bosses have Lega medals

### ISSUE THREAD

**Issue by Slothgang** [acidphantasm/acidphantasm-apbs#39]
Having your "Bosses have Lega medals" mod as a toggle inside ABPS would be cool.

**Comment by acidphantasm** [comment]
Can you clarify?

**Comment by Slothgang** [comment]
Sure, it would be adding lega medals to boss inventory loot as seen in your "Bosses Have Lega Medals" mod, with a config setting to toggle it on and off.

**Comment by acidphantasm** [comment]
Implemented with https://github.com/acidphantasm/acidphantasm-apbs/commit/f31e547cf12e1f9780a0e16e941561ef215cc63d

(It's also way better than the standalone mod until I update that)

**Comment by Slothgang** [comment]
Awesome man
