### ISSUE TITLE
Blacklist entire mods

### ISSUE THREAD

**Issue by Slothgang** [acidphantasm/acidphantasm-apbs#40]
A way to blacklist entire mods would be useful for load order management as you could freely manage load order for other mods (such as mods that alter loot) and have APBS as a late loader. I don't know if this is possible though.

Additonaly/alternatively a blacklist for individual mod added items/weapons would be amazing.

**Comment by acidphantasm** [comment]
Unfortunately this is not something that I can implement without spending probably 200+ hours going through every mod on the hub and building code specifically to check and enable/disable things. While I could do it, it creates a gigantic technical debt and many issues each time a single mod updates.

**Comment by Slothgang** [comment]
Ah yeah that wouldn't work at all, thanks for getting back to me about it though
