### ISSUE TITLE
BUG: Only TAC30 and Vudu is in the pool

### ISSUE THREAD

**Issue by DenkiBrandi** [acidphantasm/acidphantasm-apbs#43]
![image](https://github.com/user-attachments/assets/c901d01a-6d8e-4d56-98c1-139c8e93804c)
Scrolled around in these codes and find it out. Probably this is the reason why I only find TAC30 and Vudu spawned on bots?

**Comment by acidphantasm** [comment]
Fixed with https://github.com/acidphantasm/acidphantasm-apbs/commit/3f96941b0e921c3f48d19252c173b78f2d1bfc2b

**Comment by acidphantasm** [comment]
I have no idea how these didn't save the first time i tiered them. My apologies!
