### ISSUE TITLE
RECOMMENDATION: Tier 7 Bots (Both PMC and SCAVS) use the T-7 Thermal Goggles

### ISSUE THREAD

**Issue by TheRazgrizXX** [acidphantasm/acidphantasm-apbs#44]
As the title suggests, one recommendation that I could give you is to make it to where Tier 7 AI (both PMCs and SCAVs) have the possibility of using the T-7 Thermal Goggles (entire name is "T-7 Thermal Goggles with a Night Vision Mount") when it is night time. Understandably, this may mess up the "weight" of certain items, but then again Tier 7 bots are supposed to be the end-game content that one faces against when using this mod. In order to assist you, I have used the Linked Search option to find all the parts that are necessary in order for one to put on the T-7 Thermal Goggles. As you will see below, I have typed all the helmets/gear connections, then the associated mounts, and finally the goggles themselves.

- Gear Components

1. Diamond Age Bastion helmet armor plate
2. Tac-Kek Heavy Trooper mask for Ops-Core-Type hemlets

- Headgear

1. 6B47 Ratnik-BSh helmet (Digital Flora cover)
2. 6B47 Ratnik-BSh helmet (Olive Drab)
3. BNTI LShZ-2DTM helmet (Black)
4. Crye Precision AirFrame helmet (Tan)
5. Diamond Age Bastion helmet (Black)
6. Diamond Age NeoSteel High Cut helmet (Black)
7. Galvion Caiman Hybrid helmet (Grey)
8. LShZ lightweight helmet (Olive Drab)
9. MSA ACH TC-2001 MICH Series helmet (Olive Drab)
10. MSA ACH TC-2002 MICH Series helmet (Olive Drab)
11. MSA Gallet TC 800 High Cut combat helmet (Black)
12. NFM HJELM helmet (Hellhound Grey)
13. NPP KIASS Tor-2 helmet (Olive Drab)
14. Ops-Core FAST MT Super High Cut helmet (Black)
15. Ops-Core FAST MT Super High Cut helmet (Urban Tan)
16. Tac-Kek FAST MT helmet (Replica)
17. Team Wendy EXFIL Ballistic Helmet (Black)
18. Team Wendy EXFIL Ballistic Helmet (Coyote Brown)
19. Wilcox Skull Lock head mount

- Mounts (Part that actually attaches to the helmet)

1. Norotos Titanium Advanced Tactical Mount

- Mounts (Part that the goggles themselves attach to)

1. PVS-7 Wilcox Adapter

- The Goggles Themselves

1. T-7 Thermal Goggles with a Night Vision Mount

Hopefully the information seen above is helpful, and hopefully you are able to implement such a recommendation in order to show just how tough Tier 7 bots look like (have all the high-end gear that makes them a very credible threat to the player).

**Comment by acidphantasm** [comment]
I'll think on this and see if it's something I want to implement. Right now the thermal optics and T-7 are removed from the pools and blacklisted to prevent a rush of wealth to the player.

If it's implemented it would need to be a configuration option. I'll add it to the tracker.

**Comment by TheRazgrizXX** [comment]
If it is something you are not willing to implement, I would—at the very least—have an easy-to-follow guide for users who wish to add certain pieces of gear/attachments to this amazing mod.

**Comment by acidphantasm** [comment]
Implemented via config option
https://github.com/acidphantasm/acidphantasm-apbs/commit/02ba46485a505ecf6eda080adc459cd9e876c69c
