### ISSUE TITLE
BUG: blacklist categories

### ISSUE THREAD

**Issue by Slothgang** [acidphantasm/acidphantasm-apbs#45]
Remove melee and sidearm categories from equipment blacklist
Add melee category to weapon blacklist

**Comment by acidphantasm** [comment]
It's actually more taxing and work to remove melee and sidearm from the equipment blacklist (I'll leave it cause it doesn't hurt anything)

But melee on weapon blacklist is fixed with https://github.com/acidphantasm/acidphantasm-apbs/commit/3cbe3664465eefe4608d3610e4035f351c43d195
