### ISSUE TITLE
FIX: Make MDR spawn with their original parts.

### ISSUE THREAD

**Issue by DenkiBrandi** [acidphantasm/acidphantasm-apbs#46]
Similar request like G17/G19X one. Sometimes...well quite frequently MDR will spawn with interchangable parts of another caliber version。
![MDR issue](https://github.com/user-attachments/assets/bfa7d1bc-ae43-443e-9cfc-f0b53b1d2794)
Picture is not an actual build found from raid, it's just an example.

**Comment by acidphantasm** [comment]
Fixed with https://github.com/acidphantasm/acidphantasm-apbs/commit/fa5aa7a017cd0abdb578b581872e48febeb7b77f
