### ISSUE TITLE
FEATURE: REALISM GAS issue

### ISSUE THREAD

**Issue by NICKNMPLOL** [acidphantasm/acidphantasm-apbs#47]
Since bots never spawn with gasmasks , atleast ive never seen it. and since they dont have filters i assume if they did; all bots choke to death if you have realism on. on a lot of areas. including the entirety of labs.
Possible to make a config option that enables gasmasks with filters? espiscally on labs?
Sorry i know its a hassle, but realisms loadout system is so trash and yours is creme de la creme.

**Comment by acidphantasm** [comment]
Implemented with https://github.com/acidphantasm/acidphantasm-apbs/commit/523448f5a69b5601c4e9204e2d6a114920f1e586
