### ISSUE TITLE
BUG: Kel-Tec RFB rifle not spawning with any optics or even iron sights

### ISSUE THREAD

**Issue by TheRazgrizXX** [acidphantasm/acidphantasm-apbs#48]
Just as the title states, the Kel-Tec RFB bullpup rifle does not appear to spawn with any optical attachments or even iron sights. This has happened before, but most recently I was doing a Tier 7 only SCAV run and I found the rifle seen in the image attached to this message.
![Screenshot (180)](https://github.com/user-attachments/assets/99167f7a-59e6-4f79-aeca-c2b4f32f9ad8)

**Comment by acidphantasm** [comment]
Should be better with https://github.com/acidphantasm/acidphantasm-apbs/commit/5e72f462505f03c9fba87fde11e3f99e05357c1f

Unfortuantely, wonderful BSG, made the optic mount for the RFB be mod_mount and not scope like everything else
