### ISSUE TITLE
BUG: Raiders spawn with a 5-7 with the RMR mount but missing the reflex sight

### ISSUE THREAD

**Issue by 5-7RMR** [acidphantasm/acidphantasm-apbs#51]
Raiders spawn with a 5-7 with the FN Five-seveN MK2 RMR mount but missing Trijicon RMR reflex sight.

**Comment by acidphantasm** [comment]
Fixed with https://github.com/acidphantasm/acidphantasm-apbs/commit/2f7d92bab2e0dbab05851fc231c8fbbfb11fb1ec
