### ISSUE TITLE
BUG: Optics and scopes issues

### ISSUE THREAD

**Issue by hellchickens** [acidphantasm/acidphantasm-apbs#53]
1. SVD still have chance to get dual optics if axion cobra and SVD SAG MK1 chassis are rolled
2. long weapons often have optics + red dot on top of it, which is kinda weirdo, though still can exist. But logic is broken as there are in most cases 1-6, 1-8 and 3-15 scopes with red dots on tops, but all things with 10x+ are not

**Comment by acidphantasm** [comment]
Can you give me an example of the SVDS spawning with the Kobra? I'm not seeing that in the mod pools for any attachments for the SVDS but I could be blind.

**Comment by acidphantasm** [comment]
Scope mount + red dot on top is mostly fixed logic wise (this was base SPT code causing it)
