### ISSUE TITLE
feature request ; option to change scav pistol ONLY frequency

### ISSUE THREAD

**Issue by NICKNMPLOL** [acidphantasm/acidphantasm-apbs#64]
title, 
want to make more scavs have only pistol, espiscally with imported mod weapons but just in general as well. seems i can find no such option, is it possible to make such a option bar or something the likes ?

in my mind most common fire arm would defo be pistols of all kinds. among scavs, cause of low price.
so i want to make it more frequent basically that scavs only have pistols and just that.

**Comment by acidphantasm** [comment]
You would need to make a custom preset and adjust the chances of scavs
having pistols to 100% and then change their primary/secondary weapon to 0%.

This is not a feature that will be implemented in default APBS as it's
already handled if you create a preset.

**Comment by NICKNMPLOL** [comment]
Which is the default preset? so  i can just modify that ? is it example ?

**Comment by NICKNMPLOL** [comment]
And in which file sir can i ask that? im looking at tier(x)_chances rn, and i can not find any secondary weapon or pistol slot.. what i can however find is a holster slot ? is this the pistol chance i have to increase?

**Comment by acidphantasm** [comment]
Holster is pistol slot, yes
