### ISSUE TITLE
Potential Tier Blending

### ISSUE THREAD

**Issue by rube-romp** [acidphantasm/acidphantasm-apbs#69]
I have no other mods which influence bot loadouts or progression, APBS is configured to load last as per instructions.

I'm noticing bots having equipment which _seems to me_ of a higher tier (Player level 16). M4's on low tier bots have attachments that seem above their level would be one example. Reshala's guards have very well equipped weapons with many attachments (including IR devices). I also found a scav with an MDR, it had lowered durability and no reason to suspect it was picked up. Is this normal? Thank you!

**Comment by acidphantasm** [comment]
Bosses and guards will always have better equipment. Scavs can absolutely spawn with a low durability MDR (but it's a low chance).

This is all normal for APBS, you can adjust all of these variables by making a preset or adjusting the config.
